src/main/java/com/drunkenlion/alcoholfriday/domain/cart/entity/Cart.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/entity/CartDetail.java

- Member OneToOne 설정
- cartDetail OneToMany 설정
- Cart 내 Member 생성할 수 있는 create 메소드 생성 (주석 표기)
- 외래키 설정 x
- 수량 기본 값 0 설정

[AF-30] feat: Cart 관련 Entity 구현

---

src/main/java/com/drunkenlion/alcoholfriday/domain/item/dto/SearchItemResponse.java
src/test/java/com/drunkenlion/alcoholfriday/domain/item/api/ItemControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/item/application/ItemServiceTest.java

응답값에 price를 누락한 버그가 발생하였고 수정했습니다.

[af-39] bug: price 항목 누락

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/api/AdminController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminCustomerService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminCustomerServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberServiceImpl.java

[af-47] feat: 관리자 도메인 package 구조 세팅

---

src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileService.java
src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/global/file/dao/FileRepository.java
src/main/java/com/drunkenlion/alcoholfriday/global/ncp/application/NcpS3Service.java
src/main/java/com/drunkenlion/alcoholfriday/global/ncp/application/NcpS3ServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/global/ncp/dto/NcpFileResponse.java

파일 엔티티 구조가 변경됨에 따라 Json 필드에 파일 정보들이 저장되게끔 수정하였습니다.

[af-23] 파일 엔티티 구조 변경에 따른 저장 방식 변경

---

src/main/java/com/drunkenlion/alcoholfriday/global/common/enumerated/OrderStatus.java

구매 프로세스 확정으로 인한 주문 상태값을 추가하였습니다.

[af-52] feat: 주문 상태 추가

---

src/main/java/com/drunkenlion/alcoholfriday/domain/item/entity/Item.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/entity/ItemProduct.java
src/main/java/com/drunkenlion/alcoholfriday/domain/maker/entity/Maker.java
src/main/java/com/drunkenlion/alcoholfriday/domain/order/entity/Order.java
src/main/java/com/drunkenlion/alcoholfriday/domain/product/entity/Product.java
src/main/java/com/drunkenlion/alcoholfriday/global/common/enumerated/ItemType.java

item
item_product
maker
product
orders
order_detail
Entity Mapping 변경 사항 추가했습니다.

[AF-54] feat: entity mapping 변경

---

src/main/java/com/drunkenlion/alcoholfriday/domain/address/entity/Address.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/entity/Cart.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/entity/CartDetail.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/entity/Answer.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/entity/Notice.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/entity/Question.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/entity/Member.java

Customer Service 내 공지사항 엔티티 추가

[AF-54] feat: entity 생성 및 수정

---

Dockerfile
build.gradle
compose.yaml

docker에 필요한 file을 설정합니다.
자세한 내용은 컨플루언스에 설명하였습니다.

[af-55] build: docker setting

---

src/main/java/com/drunkenlion/alcoholfriday/domain/category/dao/CategoryClassRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/dto/FindCategoryResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/entity/Category.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/dao/ItemRepositoryImpl.java
src/test/java/com/drunkenlion/alcoholfriday/domain/item/api/ItemControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/item/application/ItemServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/item/dao/ItemRepositoryTest.java

[af-58] feat: entity 변경으로 인한 로직 변경

---

src/test/java/com/drunkenlion/alcoholfriday/domain/item/application/ItemServiceTest.java

단위 테스트는 다음과 같은 원칙이 있습니다.
- Fast : 테스트는 빠르게 동작하고 자주 가동 해야한다.
- Independent : 각각의 테스트는 독립적어이야 하며, 서로에 대한 의존성은 없어야 한다.
- Repeatable : 어느 환경에서도 반복이 가능해야 한다.
- Self-Validating : 테스트는 성공 또는 실패 값으로 결과를 내어 자체적으로 검증 되어야 한다.
- Timely : 테스트는 테스트 하려는 실제 코드를 구현하기 직전에 구현 해야한다.
기존 단위 테스트의 경우 @SpringBootTest를 사용하여 Spring의 환경을 불러와야 했습니다.
하지만 이는 규칙중 하나인 Fast에 위반되어서 Mock에 대해 조사하고 적용하였습니다.

[af-59] test: Mock 추가

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/api/AdminController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/dto/MemberListResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/dao/MemberRepository.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/api/AdminControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberServiceTest.java

관리자 회원관리화면의 전체 회원 조회 기능을 추가하였습니다.
Controller, Service Test code도 추가 하였습니다.

[AF-57] feat: admin - 전체 회원 조회 기능 구현

---

src/main/java/com/drunkenlion/alcoholfriday/domain/provision/entity/Provision.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/entity/Restaurant.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/entity/RestaurantStock.java

Restaurant Class Comment 추가  
Provision Class Comment 추가 
RestaurantStock Class Comment 추가

[af-54] @Comment 업데이트 

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/api/AdminController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/dto/MemberDetailResponse.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/api/AdminControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/application/AdminMemberServiceTest.java

회원 상세 조회 기능 구현
회원 상세 조회 테스트 구현

[AF-69] 관리자 회원관리 - 회원 상세 조회 기능 구현

---

build.gradle

Swagger gradle 추가 
- Swagger UI를 이용하여 API 호출 시 프런트로부터 전달해야 할 파라미터를 문서화로 불 수 있도록 추가

[af-16] feat: Swagger Gradle 추가 

---

src/main/java/com/drunkenlion/alcoholfriday/global/common/enumerated/EntityType.java

Entity Type을 Enum으로 관리하기 위해서 추가하였습니다.

[af-53] feat: file 저장에 따른 Entity Type 정의

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/api/AdminController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/dto/MemberDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/dto/MemberListResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/dto/RestaurantDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/dto/RestaurantListResponse.java

관리자 쪽에 Swagger 적용해 보았습니다.
dto쪽에 schema 세팅하고
Controller 쪽에 Tag, Operation 만 추가했습니다.
naming 룰 이런식으로 하면 될지 확인 부탁드립니다!

[AF-79] feat: 관리자 도메인 Swagger 적용

---

Dockerfile
compose.yaml

docker setting에 문제가 있던 부분을 수정하였습니다.

[af-55] build: docker setting done

---

src/main/java/com/drunkenlion/alcoholfriday/AlcoholfridayApplication.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/api/AdminMemberController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/application/AdminMemberService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/application/AdminMemberServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/dto/MemberModifyRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/entity/Member.java
src/main/java/com/drunkenlion/alcoholfriday/global/common/entity/BaseEntity.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/member/api/AdminMemberControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/member/application/AdminMemberServiceTest.java

[af-70] feat: admin - 회원 수정 기능 구현

---

src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileServiceImpl.java
src/test/java/com/drunkenlion/alcoholfriday/domain/item/api/ItemControllerTest.java

[af-59] test: test code 수정

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/dao/RestaurantStockRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/entity/RestaurantStock.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceTest.java

- 매장 삭제 기능 구현
- 매장 삭제 기능 테스트 구현

[af-75] feat: admin - 매장 삭제 기능 구현

---

src/main/java/com/drunkenlion/alcoholfriday/global/common/enumerated/EntityType.java
src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileService.java
src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileServiceImpl.java

[AF-120] refactor: 이미지 find method 매개변수 수정

---

src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileService.java
src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileServiceImpl.java

1. method 매개변수 타입 수정
- String entityType -> EntityType entityType

[af-122] refactor: File upload method 매개변수 타입 수정

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/dto/RestaurantDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/dto/RestaurantStockItemResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/dao/RestaurantStockRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/entity/Restaurant.java
src/main/java/com/drunkenlion/alcoholfriday/global/ncp/dto/NcpFileResponse.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantControllerTest.java

- admin - 매장 상세 조회 판매중인 상품 정보 기능 추가
- restaurant entity @Builder.Default 처리
- NcpFileResponse 빌더에 entityId, entityType 추가
- admin - 매장 수정 테스트 추가

[af-72] 관리자 매장관리 - 매장 상세 조회의 판매 중인 상품 가져오기

---

src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/api/QuestionController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/application/QuestionService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/application/QuestionServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/dto/request/QuestionRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/dto/request/QuestionSaveRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/dto/response/AnswerResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/dto/response/QuestionResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/dto/response/QuestionSaveResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/entity/Answer.java
src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileService.java
src/main/java/com/drunkenlion/alcoholfriday/global/file/application/FileServiceImpl.java

- [이미지 저장 기능 구현 중 문제점에 대한 정리 게시물](https://seop-official.tistory.com/entry/SpringBoot-Rest-API%EC%97%90%EC%84%9C-jsondto%EA%B3%BC-multipart-%EB%8F%99%EC%8B%9C%EC%B2%98%EB%A6%AC)

[af-108] feat: 문의사항 등록 기능 구현

---

.github/workflows/cd.yml
Dockerfile
compose.yaml
deploy-server.sh

build: cd 스크립트 작성 완료

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/api/AdminStoreItemController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/application/AdminStoreItemService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/application/AdminStoreItemServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/dto/ItemDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/dto/ItemListResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/dto/ItemProductInfo.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/dto/ItemRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/dao/CartDetailRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/entity/CartDetail.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/dao/CategoryRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/dao/ItemProductRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/dao/ItemRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/entity/Item.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/entity/ItemProduct.java
src/main/java/com/drunkenlion/alcoholfriday/domain/product/dao/ProductRepository.java
src/main/java/com/drunkenlion/alcoholfriday/global/common/response/HttpResponse.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/api/AdminStoreItemControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/store/item/application/AdminStoreItemServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/store/product/api/AdminStoreProductControllerTest.java

- 상품 전체 목록 조회 기능
- 상품 상세 조회 기능
- 상품 등록 기능
- 상품 수정 기능
- 상품 수정 시 item에 관련된 기존 itemProduct는 모두 논리적 삭제 후 수정에 등록된 itemProduct가 모두 insert됨
- 상품 삭제 기능
- 상품 삭제 시 관련 itemProduct, cartDetail 논리적 삭제됨
- 상품 Test 추가

[af-117] feat: admin - 스토어 상품 관련 기능 구현 

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/api/AdminCategoryController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/application/AdminCategoryClassService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/application/AdminCategoryClassServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/application/AdminCategoryService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/application/AdminCategoryServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/dto/CategoryClassDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/dto/CategoryClassListResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/dto/CategoryClassRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/dto/CategoryDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/dto/CategoryListResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/dto/CategoryRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/api/AdminItemController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/dao/CategoryClassRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/dao/CategoryRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/entity/Category.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/entity/CategoryClass.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/dao/ItemRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/product/dao/ProductRepository.java
src/main/java/com/drunkenlion/alcoholfriday/global/common/response/HttpResponse.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/category/api/AdminCategoryControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/category/application/AdminCategoryClassServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/category/application/AdminCategoryServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/item/application/AdminItemServiceTest.java

- 대분류 전체 목록 조회 기능
- 대분류 상세 조회 기능
- 대분류 등록 기능
- 대분류 수정 기능
- 대분류 삭제 기능
- 대분류의 소분류들과 관계가 있는 item, product 중 삭제 상태가 아닌 것이 있는지 확인
- 소분류 전체 목록 조회 기능
- 소분류 상세 조회 기능
- 소분류 등록 기능
- 소분류 수정 기능
- 소분류 삭제 기능
- 소분류와 관계가 있는 item, product 중 삭제 상태가 아닌 것이 있는지 확인
- 카테고리 Test 추가

[af-118] feat: admin - 스토어 카테고리 관련 기능 구현

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/api/AdminItemController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/application/AdminItemService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/application/AdminItemServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/dto/ItemCreateRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/dto/ItemDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/dto/ItemModifyRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/api/AdminProductController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/application/AdminProductService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/application/AdminProductServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/dto/ProductCreatRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/dto/ProductCreateRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/dto/ProductDetailResponse.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/dto/ProductModifyRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/dto/RestaurantStockItemResponse.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/item/api/AdminItemControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/item/application/AdminItemServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/product/api/AdminProductControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/product/application/AdminProductServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantControllerTest.java

- 매장의 상품 (조회)
- 제품 (조회, 등록, 수정)
- 상품 (조회, 등록, 수정)
- 주문의 상품 (조회) -> 해당 기능은 다음 branch에서 적용하겠습니다.
- 새로운 이미지 기능 적용에 따른 Test 코드도 수정이 필요하였고, 기능 구현 중 어려움이 있었던 부분은 아래와 같이 정리하였습니다. 참고 바랍니다.
- [MultipartFile을 이용한 파일 업로드와 함께 전송되는 DTO 데이터 테스트](https://velog.io/@newvelog/MultipartFile%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8)
- [MultipartFile 를 HTTP PUT으로 보내기](https://velog.io/@newvelog/MultipartFile-%EB%A5%BC-HTTP-PUT%EC%9C%BC%EB%A1%9C-%EB%B3%B4%EB%82%B4%EA%B8%B0)

[af-156] feat: 새로운 이미지 기능 admin 적용

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/api/AdminMemberController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/application/AdminMemberService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/application/AdminMemberServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/dto/MemberModifyRequest.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantService.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/dao/MemberRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/dao/MemberRepositoryCustom.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/dao/MemberRepositoryImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/dao/RestaurantRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/dao/RestaurantRepositoryCustom.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/dao/RestaurantRepositoryImpl.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/member/api/AdminMemberControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/member/application/AdminMemberServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/member/dao/MemberRepositoryTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/restaurant/dao/RestaurantRepositoryTest.java
src/test/java/com/drunkenlion/alcoholfriday/global/user/WithAccount.java
src/test/java/com/drunkenlion/alcoholfriday/global/user/WithAccountSecurityContextFactory.java

- 회원 관리 권한 처리
- 회원 전체 조회 queryDsl 사용해 권한 처리
- 회원 상세 조회, 수정은 서비스 단에서 권한 처리
- 테스트 코드 변경
- 매장 관리 권한 처리
- 매장 전체 조회 queryDsl 사용해 권한 처리
- 매장 상세 조회, 등록, 수정, 삭제는 서비스 단에서 권한 처리
- 테스트 코드 변경

[af-158] feat: admin - 도메인 별 권한 처리

---

src/test/resources/application-test.yml

[Yml 파일 설정 문서](https://drunkenlion.atlassian.net/wiki/spaces/A/pages/7176206/yml)
위 내용 참고하여 자신의 로컬 접속 계정을 application-secret.yml 에 추가하기 바랍니다.

[af-165] chore: TEST 환경에서 Mysql local db 연결을 위한 설정 변경

---

src/main/java/com/drunkenlion/alcoholfriday/domain/address/api/AddressController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/category/api/AdminCategoryController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/api/AdminItemController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/maker/api/AdminMakerController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/api/AdminMemberController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/api/AdminProductController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/api/CartController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/api/QuestionController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/api/MemberController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/api/RestaurantController.java
src/main/java/com/drunkenlion/alcoholfriday/global/config/SpringDocConfig.java

SecurityConfig 를 참고해 권한이 필요한 api에 Swagger 인증 버튼을 셋업하였습니다.
코드 참고하셔서 누락되었거나 잘못된 부분이 있다면 코멘트 부탁드립니다.

[af-176] docs: swagger bearerAuth 버튼 셋업

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/item/api/AdminItemController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/maker/api/AdminMakerController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/maker/application/AdminMakerServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/member/api/AdminMemberController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/api/AdminProductController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/product/application/AdminProductServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantController.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/util/RestaurantDataValidator.java
src/main/java/com/drunkenlion/alcoholfriday/domain/maker/dao/MakerRepository.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/dao/MemberRepositoryImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/dao/RestaurantRepositoryImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/enumerated/DayInfo.java
src/main/java/com/drunkenlion/alcoholfriday/global/common/util/JsonConvertor.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/category/api/AdminCategoryControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/item/api/AdminItemControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/item/application/AdminItemServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/maker/api/AdminMakerControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/maker/application/AdminMakerServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/member/api/AdminMemberControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/product/api/AdminProductControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/product/application/AdminProductServiceTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/api/AdminRestaurantControllerTest.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/application/AdminRestaurantServiceTest.java

- find 쿼리 삭제 조건 추가
- `findById` -> `findByIdAndDeletedAtIsNull`
- 매장 정보 validator 리펙토링
- getMapping 엔드포인트 단순화
- paging 쿼리에 누락된 offset 추가
- 누락된 테스트 추가 및 값 변경
- 상품 삭제 실패 - 찾을 수 없는 상품
- 매장 상세 조회 성공 - OWNER 데이터로 변경
- 사용하지 않는 provision 삭제
- 사용하지 않는 util package 제거
- admin test에 jsonConvertor 적용

[af-164] refector: 관리자 기능 전체 refectoring

---

src/main/java/com/drunkenlion/alcoholfriday/domain/address/entity/Address.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/entity/Cart.java
src/main/java/com/drunkenlion/alcoholfriday/domain/cart/entity/CartDetail.java
src/main/java/com/drunkenlion/alcoholfriday/domain/category/entity/Category.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/entity/Answer.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/entity/Question.java
src/main/java/com/drunkenlion/alcoholfriday/domain/customerservice/notice/entity/Notice.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/entity/Item.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/entity/ItemProduct.java
src/main/java/com/drunkenlion/alcoholfriday/domain/maker/entity/Maker.java
src/main/java/com/drunkenlion/alcoholfriday/domain/member/entity/Member.java
src/main/java/com/drunkenlion/alcoholfriday/domain/order/entity/Order.java
src/main/java/com/drunkenlion/alcoholfriday/domain/order/entity/OrderDetail.java
src/main/java/com/drunkenlion/alcoholfriday/domain/payment/entity/Payment.java
src/main/java/com/drunkenlion/alcoholfriday/domain/product/entity/Product.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/entity/Restaurant.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/entity/RestaurantStock.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/order/entity/RestaurantOrderDetail.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/refund/entity/RestaurantOrderRefund.java
src/main/java/com/drunkenlion/alcoholfriday/domain/restaurant/refund/entity/RestaurantOrderRefundDetail.java
src/main/java/com/drunkenlion/alcoholfriday/global/ncp/entity/NcpFile.java
src/main/java/com/drunkenlion/alcoholfriday/global/security/jwt/entity/RefreshToken.java

컨플루언스와 DB 정보, ERD cloude의 DB 정보와 동일하게 맞추기 위해 entity 전체를 확인해 수정하는 작업을 진행하였습니다.

[af-201] feat: DB 변경에 따른 Entity 수정 작업

---

src/main/java/com/drunkenlion/alcoholfriday/domain/item/application/ItemServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/domain/item/dto/SearchItemResponse.java
src/test/java/com/drunkenlion/alcoholfriday/domain/item/api/ItemControllerTest.java

- findAllByEntityIds(List<Long> entityIds, String entityType) => findAll(BaseEntity entity)
- findByEntityId(Long entityId, String entityType) => findOne(BaseEntity entity)
<br>
- 메서드 수정으로 인해 아이템당 파일이미지가 다른 아이템도 같이 들어오게 되어서
아이템 하나당 파일 이미지 불러올 수 있게 변경
<br>
- 테스트를 위해서 와인, 소주 데이터 추가
- 이미지가 포함된 item 과 이미지가 없는 item 검색 테스트

[af-199] FileService에서 @Deprecated 되는 메서드로 인해서 ItemServiceImpl 수정

---

src/main/java/com/drunkenlion/alcoholfriday/domain/auth/application/AuthServiceImpl.java
src/main/java/com/drunkenlion/alcoholfriday/global/security/jwt/application/TokenService.java
src/main/java/com/drunkenlion/alcoholfriday/global/security/jwt/application/TokenServiceImpl.java

로그인을 반복할 경우 리프레시 토큰이 다중 생성되는 문제를 해결했습니다.

[af-245] fix: 리프레시 토큰이 다중 생성되는 문제 해결

---

src/main/java/com/drunkenlion/alcoholfriday/global/security/config/SecurityConfig.java

공지사항 조회, 공지사항 관리, 레스토랑 조회에 대한 권한을 추가하였습니다.

[af-114] refactor: 공지사항 및 레스토랑 관련 권한 추가

---

src/main/java/com/drunkenlion/alcoholfriday/domain/member/dto/MemberResponse.java

로그인 시 반환 객체 내 MemberRole 필드 추가

[af-320] feat: Response 내 MemberRole 필드 추가

---

src/main/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/order/api/RestaurantOrderController.java
src/main/java/com/drunkenlion/alcoholfriday/global/common/response/HttpResponse.java
src/main/java/com/drunkenlion/alcoholfriday/global/exception/GlobalExceptionHandler.java
src/test/java/com/drunkenlion/alcoholfriday/domain/admin/restaurant/order/api/RestaurantOrderControllerTest.java

1. restaurantId를 Path로 받는 방식에서 Parameter로 받도록 변경했습니다.
2. MissingServletRequestParameterException 예외 처리를 추가했습니다.

[af-268] feat: restaurantId 받는 방식 변경에 따른 GlobalExceptionHandler Exception 추가
